name: Invitation to the GitHub Community Organization
description: I would like to be part of IgPlugin
title: "Please invite me to the GitHub Community Organization"
labels: [invite]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
